### ISSUE TITLE
Is dynamixel motors handling still necessary?

### ISSUE THREAD

**Issue by simheo** [pollen-robotics/reachy2-sdk#135]
Currently there is a module [dynamixel_motor.py](https://github.com/pollen-robotics/reachy2-sdk/blob/develop/src/reachy2_sdk/dynamixel_motor.py) and a [stream](https://github.com/pollen-robotics/reachy2-sdk/blob/5735d27646aaf98035b42332b69085a907d4c171/src/reachy2_sdk/reachy_sdk.py#L427-L452) defined to handle command with Dynamixel motors.
It was originally implemented to interact with the Dynamixel motors of the gripper and antennas. Actually, the api gripper implementation only defines more high level orders like open / close meaning we don't interact in the sdk client with the gripper motor.
If the same choice is made for the antennas, we won't need to dynamixel module anymore.

**Comment by FabienDanieau** [comment]
remove in #292 during code cleanup. We'll add them back depending on the requirements for the new antennas
