### ISSUE TITLE
Check if we can open multiple connection to the same Reachy.

### ISSUE THREAD

**Issue by simheo** [pollen-robotics/reachy2-sdk#138]
We need to check if we can open multiple connection to the same Reachy in the same Python kernel. 
Note that we would need to disable the singleton decorator on ReachySDK. 

If we can do it, we will remove the singleton decorator.

If not, we should think about another way to prevent two connections on the same robot in the kernel so that we can still connect to two different Reachys in the same kernel.

**Comment by FabienDanieau** [comment]
Problem solved with #309
