### ISSUE TITLE
Refacto poll_waiting_comands.

### ISSUE THREAD

**Issue by simheo** [pollen-robotics/reachy2-sdk#140]
In ReachySDK, [poll_waiting_2dcommands](https://github.com/pollen-robotics/reachy2-sdk/blob/5735d27646aaf98035b42332b69085a907d4c171/src/reachy2_sdk/reachy_sdk.py#L277) and [poll_waiting_3dcommands](https://github.com/pollen-robotics/reachy2-sdk/blob/5735d27646aaf98035b42332b69085a907d4c171/src/reachy2_sdk/reachy_sdk.py#L304) are almost identical. There is probably a way to make it generic.

**Comment by glannuzel** [comment]
I close the issue as they do not exist anymore
