### ISSUE TITLE
Clarify/update disconnect/connect procedure

### ISSUE THREAD

**Issue by RemiFabre** [pollen-robotics/reachy2-sdk#182]
This fails:
```
reachy = ReachySDK(host="localhost")
reachy.disconnect()
reachy = ReachySDK(host="localhost")
```
This works:
```
reachy = ReachySDK(host="localhost")
reachy.disconnect()
ReachySDK.clear()
reachy = ReachySDK(host="localhost")
```
This (I think) works:
```
reachy = ReachySDK(host="localhost")
reachy.disconnect()
reachy.connect()
```

I think this is OK, it just has to be clear for the user. Suggestions :
- Give an example where several sdk clients are used
- In the error message, suggest the use of "ReachySDK.clear()"

**Comment by glannuzel** [comment]
Should be fixed by the previous merged
