### ISSUE TITLE
Forward kinematics cannot be spammed.

### ISSUE THREAD

**Issue by simheo** [pollen-robotics/reachy2-sdk#283]
When calling 
```python
reachy.l_arm.forward_kinematics()
```
at 1Hz, the fk returns always the same results, even if the arm is moving whereas calling
```python
reachy.l_arm.forward_kinematics(reachy.l_arm.get_joints_positions())
```
works.

**Comment by glannuzel** [comment]
We do not manage to reproduce the issue so far, we'll see if it is back in specific conditions
